branches:
  only:
  - back/go/main

matrix:
  include:
    - language: go

      go:
        - 1.9.2

      install: 
        - mkdir -p $GOPATH/src/github.com/RepGarage
        - ln -s $GOPATH/src/github.com/RepGarage/go
        - cd back/go/main && ./install-deps.sh
      services:
        - mongodb

      script: go test ./... -cover

      after_success: ./deploy-docker.sh