matrix:
  include:
    - if: branch =~ back/go/main
    
      language: go

      go:
        - 1.9.2
      services:
        - mongodb

      install: 
        - mkdir -p $GOPATH/src/github.com/RepGarage
        - ln -s $GOPATH/src/github.com/RepGarage/go
        - cd back/go/main && ./install-deps.sh

      script: go test ./... -cover

      after_success: ./deploy-docker.sh

    - if: branch =~ front/ts/main
    
      language: javascript

      script: front/ts/main/deploy-docker.sh
