matrix:
  include:
    language: go

    go:
      - 1.9.2

    install: 
      - mkdir -p $GOPATH/src/github.com/RepGarage
      - ln -s $GOPATH/src/github.com/RepGarage/go
      - cd back/go/main && ./install-deps.sh

    script: go test -cover